[package]
name = "git_common"
version = "0.1.0"
authors = ["Henrik Södergren <henrik.sodergren@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "*"
structopt = "*"
